//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuthority_RuleCategoryMap
    {
        public int Authority_CategoryMapId { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<int> RuleCategoryId { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
    
        public virtual tblMasAuthority tblMasAuthority { get; set; }
        public virtual tblMasRuleCategory tblMasRuleCategory { get; set; }
    }
}
