//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblPolicyClients = new HashSet<tblPolicyClient>();
            this.tblPolicies = new HashSet<tblPolicy>();
            this.tblPolicies1 = new HashSet<tblPolicy>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<decimal> AdressID { get; set; }
        public short ClientType { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string NameWithInitials { get; set; }
        public string CorporateName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string HomeNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string WorkNo { get; set; }
        public string AltEmailID { get; set; }
        public string Fax { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PassportNo { get; set; }
        public string PreferredName { get; set; }
        public string CustUniqueID { get; set; }
        public Nullable<decimal> MaritalStatusID { get; set; }
        public Nullable<decimal> NationalityID { get; set; }
        public string OLDNICNO { get; set; }
        public string NEWNICNO { get; set; }
        public string MonthlyIncome { get; set; }
        public string CompanyName { get; set; }
        public string NatureofDuties { get; set; }
        public string Citizenship1 { get; set; }
        public string Citizenship2 { get; set; }
        public string ResidentialNationality { get; set; }
        public string ResidentialNationalityStatus { get; set; }
        public Nullable<bool> OccupationHazardousWork { get; set; }
        public string PassportNumber { get; set; }
        public string DrivingLicense { get; set; }
        public string USTaxpayerId { get; set; }
        public string CountryOccupation { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyClient> tblPolicyClients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicy> tblPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicy> tblPolicies1 { get; set; }
    }
}
