//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactDetail
    {
        public decimal ContactID { get; set; }
        public Nullable<decimal> OfficeID { get; set; }
        public string Position { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SLIIRegNo { get; set; }
        public Nullable<decimal> MobileNo1 { get; set; }
        public Nullable<decimal> MobileNo2 { get; set; }
        public Nullable<decimal> OfficePhone1 { get; set; }
        public Nullable<decimal> OfficePhone2 { get; set; }
        public Nullable<decimal> ResidenceNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> OrganizationID { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
    }
}
