//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboardReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDashboardReport()
        {
            this.tblDashboardReportGraphs = new HashSet<tblDashboardReportGraph>();
            this.tblDashboardSubReports = new HashSet<tblDashboardSubReport>();
        }
    
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string ReportTitle { get; set; }
        public string ValueAxisTitle { get; set; }
        public string ValueAxisUnit { get; set; }
        public string Theme { get; set; }
        public string Type { get; set; }
        public string Height { get; set; }
        public Nullable<decimal> PlotAreaFillAlphas { get; set; }
        public Nullable<int> StartDuration { get; set; }
        public Nullable<bool> IsGrowth { get; set; }
        public Nullable<bool> Rotate { get; set; }
        public Nullable<int> LabelRotation { get; set; }
        public string Width { get; set; }
        public Nullable<bool> VALabelsEnabled { get; set; }
        public string VAPosition { get; set; }
        public string GrowthLabel { get; set; }
        public Nullable<bool> IsDrillDown { get; set; }
        public Nullable<int> depth3D { get; set; }
        public Nullable<int> angle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDashboardReportGraph> tblDashboardReportGraphs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDashboardSubReport> tblDashboardSubReports { get; set; }
    }
}
