//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashboardSubReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDashboardSubReport()
        {
            this.tblDashboardSubReports1 = new HashSet<tblDashboardSubReport>();
            this.tblDashboardXAxis = new HashSet<tblDashboardXAxi>();
        }
    
        public long SubReportID { get; set; }
        public Nullable<int> ReportID { get; set; }
        public string YAxisValue1 { get; set; }
        public string YAxisTitle { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual tblDashboardReport tblDashboardReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDashboardSubReport> tblDashboardSubReports1 { get; set; }
        public virtual tblDashboardSubReport tblDashboardSubReport1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDashboardXAxi> tblDashboardXAxis { get; set; }
    }
}
