//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblEmergencyDetails = new HashSet<tblEmergencyDetail>();
        }
    
        public decimal EmpID { get; set; }
        public string EpfNo { get; set; }
        public string EmployeeCode { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MaritalStatus { get; set; }
        public string NICNo { get; set; }
        public string Nationality { get; set; }
        public string SalesExperience { get; set; }
        public string IndustryExperience { get; set; }
        public string MobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public string OfficePhNo { get; set; }
        public Nullable<decimal> CommunicationAddressID { get; set; }
        public Nullable<decimal> PermenantAddressID { get; set; }
        public Nullable<bool> IsPerAddressSameasCommAddress { get; set; }
        public string EmergencyMobileNo { get; set; }
        public string RelationWithEmergency { get; set; }
        public string others { get; set; }
        public string PrintName { get; set; }
        public string Position { get; set; }
        public string DesignationID { get; set; }
        public string UserID { get; set; }
        public string OldEPFNo { get; set; }
        public string ReportingEmpID { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeType { get; set; }
        public string OfficeName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Email { get; set; }
        public string ResidencePhno { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblAddress tblAddress1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmergencyDetail> tblEmergencyDetails { get; set; }
    }
}
