//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmergencyDetail
    {
        public decimal EmergencyDetailId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> AddressID { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public Nullable<decimal> AltMobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> ProspectID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Relationship { get; set; }
        public string RelationshipOthers { get; set; }
        public Nullable<decimal> EmpID { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblProspect tblProspect { get; set; }
    }
}
