//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLifeQQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLifeQQ()
        {
            this.tblProposalMemberDetails = new HashSet<tblProposalMemberDetail>();
            this.tblPolicyCLAQuotes = new HashSet<tblPolicyCLAQuote>();
            this.tblQuoteDrawDownDetails = new HashSet<tblQuoteDrawDownDetail>();
            this.tblQuoteMemberDetials = new HashSet<tblQuoteMemberDetial>();
        }
    
        public int LifeQQID { get; set; }
        public int VersionNo { get; set; }
        public int ContactID { get; set; }
        public Nullable<int> PolicyTermID { get; set; }
        public Nullable<int> ProductNameID { get; set; }
        public Nullable<decimal> QQ_SumAssured { get; set; }
        public Nullable<int> PremiumPayingTermID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PremiumTerm { get; set; }
        public Nullable<int> NeedID { get; set; }
        public string QuoteNo { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string PreferredTerm { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string AnnualPremium { get; set; }
        public string HalfyearlyPremium { get; set; }
        public string QuarterlyPremium { get; set; }
        public string Monthly { get; set; }
        public string Vat { get; set; }
        public string Cess { get; set; }
        public string PolicyFee { get; set; }
        public string Createdby { get; set; }
        public string AllocatedFrom { get; set; }
        public int PlanId { get; set; }
        public string PlanCode { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public string PreferredLanguage { get; set; }
        public Nullable<int> PensionPeriod { get; set; }
        public Nullable<bool> SelfPay { get; set; }
        public Nullable<bool> IsFamilyFloater { get; set; }
        public Nullable<bool> Deductable { get; set; }
        public Nullable<int> DrawDownPeriod { get; set; }
        public Nullable<int> RetirementAge { get; set; }
        public Nullable<int> MonthlySurvivorIncome { get; set; }
        public Nullable<int> SAM { get; set; }
        public Nullable<int> AnnualizePremium { get; set; }
        public string QType { get; set; }
        public string OnGoingProposalWithAIA { get; set; }
        public string PreviousPolicyWithAIA { get; set; }
        public Nullable<int> NoOfOnGoingProposalWithAIA { get; set; }
        public Nullable<int> NoOfPreviousPolicyWithAIA { get; set; }
        public byte[] ProspectSignature { get; set; }
        public string ProposerSignPath { get; set; }
        public byte[] WPSignature { get; set; }
        public string WPPSignPath { get; set; }
        public string SignType { get; set; }
        public string MaturityBenifits { get; set; }
        public string RefNo { get; set; }
        public string IsAfc { get; set; }
        public string ModalPremium { get; set; }
        public Nullable<bool> IsTopUp { get; set; }
        public string SurrenderYear { get; set; }
        public Nullable<bool> IsSurrender { get; set; }
        public Nullable<System.DateTime> RiskCommencementDate { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProposalMemberDetail> tblProposalMemberDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyCLAQuote> tblPolicyCLAQuotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteDrawDownDetail> tblQuoteDrawDownDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteMemberDetial> tblQuoteMemberDetials { get; set; }
    }
}
