//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasILClient
    {
        public decimal ID_PK { get; set; }
        public string CLNTNUM { get; set; }
        public string SECUITYNO { get; set; }
        public string SURNAME { get; set; }
        public string GIVNAME { get; set; }
        public string CLTSEX { get; set; }
        public string CLTADDR01 { get; set; }
        public string CLTADDR02 { get; set; }
        public string CLTADDR03 { get; set; }
        public string CLTADDR04 { get; set; }
        public string CLTADDR05 { get; set; }
        public string CLTPCODE { get; set; }
        public string CLTPHONE01 { get; set; }
        public string CLTPHONE02 { get; set; }
        public string RMBLPHONE { get; set; }
        public string RINTERNET { get; set; }
        public string OCCPCODE { get; set; }
        public Nullable<int> CLTDOB { get; set; }
        public Nullable<int> CLTDOD { get; set; }
        public string MARRYD { get; set; }
        public string SALUTL { get; set; }
        public string NATLTY { get; set; }
        public string LANGE { get; set; }
        public string LSURNAME { get; set; }
        public string LGIVNAME { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SURNAMES { get; set; }
    }
}
