//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberQuestion
    {
        public decimal MemberQuestionID { get; set; }
        public decimal MemberID { get; set; }
        public int QID { get; set; }
        public string ItemType { get; set; }
        public string Answer { get; set; }
        public string SubAnswer { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string SubType { get; set; }
    
        public virtual tblPolicyMemberDetail tblPolicyMemberDetail { get; set; }
    }
}
