//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasLifeQuestionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasLifeQuestionnaire()
        {
            this.tblQuestionDetails = new HashSet<tblQuestionDetail>();
        }
    
        public int QId { get; set; }
        public string QText { get; set; }
        public string QType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Subtype { get; set; }
        public string ControlType { get; set; }
        public string SubQuestion { get; set; }
        public string SubControlType { get; set; }
        public string Gender { get; set; }
        public string Relationship { get; set; }
        public string Value { get; set; }
        public string Master { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ResidentialStatus { get; set; }
        public Nullable<bool> OccupationHazardouswork { get; set; }
        public string PAQQuestionsID { get; set; }
        public string QForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestionDetail> tblQuestionDetails { get; set; }
    }
}
