//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasIMOUser
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string AgentCode { get; set; }
        public string Channel { get; set; }
        public string NIC { get; set; }
        public string UserRole { get; set; }
        public string Branch { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public bool UserStatus { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string ReportingManager { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<int> AuthorityId { get; set; }
    }
}
