//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasProductPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasProductPlan()
        {
            this.tblProductPlanRiderDiscountLoadingMaps = new HashSet<tblProductPlanRiderDiscountLoadingMap>();
            this.tblMasPolicyTerms = new HashSet<tblMasPolicyTerm>();
            this.tblMasSAMs = new HashSet<tblMasSAM>();
            this.tblProductPlanRiders = new HashSet<tblProductPlanRider>();
        }
    
        public int PlanId { get; set; }
        public string PlanCode { get; set; }
        public string PlanDescriprion { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string RefPlanCode { get; set; }
        public Nullable<int> PremiumTerm { get; set; }
        public int CeasingAge { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPlanRiderDiscountLoadingMap> tblProductPlanRiderDiscountLoadingMaps { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasPolicyTerm> tblMasPolicyTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasSAM> tblMasSAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPlanRider> tblProductPlanRiders { get; set; }
    }
}
