//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasBasicRate
    {
        public int BasicRateID { get; set; }
        public string VehicleType { get; set; }
        public string Zone { get; set; }
        public Nullable<int> FromCC { get; set; }
        public Nullable<int> ToCC { get; set; }
        public Nullable<int> FromAge { get; set; }
        public Nullable<int> ToAge { get; set; }
        public string ItemType { get; set; }
        public string RateType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> MinPax { get; set; }
        public Nullable<int> MaxPax { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> PremPerLicensedPassen { get; set; }
    }
}
