//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasPolicyTerm
    {
        public int PolicyTermID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public int Term { get; set; }
    
        public virtual tblMasProductPlan tblMasProductPlan { get; set; }
    }
}
