//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasBenefit
    {
        public int BenefitID { get; set; }
        public string BenefitName { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> MaturityAge { get; set; }
        public string MaxSIFactor { get; set; }
        public Nullable<int> RateID { get; set; }
    }
}
