//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasLifeHierarchyTree
    {
        public int ItemId { get; set; }
        public string ItemDescription { get; set; }
        public string ItemNavUrl { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
