//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberDeviationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMemberDeviationInfo()
        {
            this.tblMemberDeviationHistories = new HashSet<tblMemberDeviationHistory>();
        }
    
        public decimal MemberDeviationID { get; set; }
        public decimal MemberID { get; set; }
        public string Code { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string Decision { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RuleId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberDeviationHistory> tblMemberDeviationHistories { get; set; }
        public virtual tblPolicyMemberDetail tblPolicyMemberDetail { get; set; }
    }
}
