//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasArea
    {
        public long Area_ID_PK { get; set; }
        public Nullable<long> City_ID_FK { get; set; }
        public Nullable<int> District_ID_FK { get; set; }
        public string Area_Name { get; set; }
        public string Pin_Code { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public string Deleted_By { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public bool Area_ARC { get; set; }
    }
}
