//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasSAM
    {
        public int SamID { get; set; }
        public Nullable<int> PlanId { get; set; }
        public int MinSAM { get; set; }
        public int MixSAM { get; set; }
        public int MinAge { get; set; }
        public int MixAge { get; set; }
    
        public virtual tblMasProductPlan tblMasProductPlan { get; set; }
    }
}
