//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNeedEducationCalculator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNeedEducationCalculator()
        {
            this.tblNeedEduHighers = new HashSet<tblNeedEduHigher>();
            this.tblNeedEduForeigns = new HashSet<tblNeedEduForeign>();
            this.tblNeedEduGCEALs = new HashSet<tblNeedEduGCEAL>();
            this.tblNeedEduLocals = new HashSet<tblNeedEduLocal>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NeedAnalysisID { get; set; }
        public Nullable<int> Inflationrate { get; set; }
        public Nullable<decimal> AnnualEduExp { get; set; }
        public Nullable<decimal> EduMaturityValue { get; set; }
        public Nullable<decimal> LumpSum { get; set; }
        public Nullable<decimal> EduGapTotal { get; set; }
        public Nullable<decimal> MonthlyEduExp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedEduHigher> tblNeedEduHighers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedEduForeign> tblNeedEduForeigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedEduGCEAL> tblNeedEduGCEALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedEduLocal> tblNeedEduLocals { get; set; }
        public virtual tblLifeNeedAnalysi tblLifeNeedAnalysi { get; set; }
    }
}
