//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNeedSaveTour
    {
        public int TourId { get; set; }
        public Nullable<int> SaveCalcID { get; set; }
        public Nullable<decimal> CurrentReq { get; set; }
        public Nullable<decimal> Term { get; set; }
        public Nullable<decimal> MaturityAge { get; set; }
        public Nullable<decimal> EstAmount { get; set; }
        public Nullable<decimal> AvailableFund { get; set; }
        public Nullable<decimal> Gap { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual tblNeedSavingCalculator tblNeedSavingCalculator { get; set; }
    }
}
