//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNeedRetirementCalculator
    {
        public int Id { get; set; }
        public Nullable<int> NeedAnalysisID { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> ToYear { get; set; }
        public Nullable<int> InflationRate { get; set; }
        public Nullable<int> PlanNoYears { get; set; }
        public Nullable<int> IntrestRate { get; set; }
        public Nullable<decimal> TotalMonthlyExp { get; set; }
        public Nullable<decimal> EstMonthlyExp { get; set; }
        public Nullable<decimal> CurrentFoodExp { get; set; }
        public Nullable<decimal> CurrentWaterExp { get; set; }
        public Nullable<decimal> CurrentRentExp { get; set; }
        public Nullable<decimal> CurrentLeaseExp { get; set; }
        public Nullable<decimal> CurrentTransportExp { get; set; }
        public Nullable<decimal> CurrentMedExp { get; set; }
        public Nullable<decimal> CurrentEduExp { get; set; }
        public Nullable<decimal> CurrentClothesExp { get; set; }
        public Nullable<decimal> CurrentEntertainmentExp { get; set; }
        public Nullable<decimal> CurrentCharity { get; set; }
        public Nullable<decimal> CurrentOtherExp { get; set; }
        public Nullable<decimal> EstFoodExp { get; set; }
        public Nullable<decimal> EstWaterExp { get; set; }
        public Nullable<decimal> EstRentExp { get; set; }
        public Nullable<decimal> EstLeaseExp { get; set; }
        public Nullable<decimal> EstTransportExp { get; set; }
        public Nullable<decimal> EstMedExp { get; set; }
        public Nullable<decimal> EstEduExp { get; set; }
        public Nullable<decimal> EstClothesExp { get; set; }
        public Nullable<decimal> EstEntertainmentExp { get; set; }
        public Nullable<decimal> EstCharity { get; set; }
        public Nullable<decimal> EstOtherExp { get; set; }
        public Nullable<decimal> CurrentMonthlySalary { get; set; }
        public Nullable<decimal> CurrentEPFBalance { get; set; }
        public Nullable<decimal> EstEPFBalance { get; set; }
        public Nullable<decimal> CurrentMonthly20Sal { get; set; }
        public Nullable<decimal> CurrentETFBalance { get; set; }
        public Nullable<decimal> EstETFBalance { get; set; }
        public Nullable<decimal> CurrentMonthly3Sal { get; set; }
        public Nullable<decimal> CurrentGratuityFund { get; set; }
        public Nullable<decimal> EstGratuityFund { get; set; }
        public Nullable<decimal> TotalEstMonthlyExpFund { get; set; }
        public Nullable<decimal> ChildEduFund { get; set; }
        public Nullable<decimal> ChildWeddingFund { get; set; }
        public Nullable<decimal> VehicleFund { get; set; }
        public Nullable<decimal> LoanFund { get; set; }
        public Nullable<decimal> OtherFund { get; set; }
        public Nullable<decimal> FundBalance { get; set; }
        public Nullable<decimal> PerAnnIncomeIntrest { get; set; }
        public Nullable<decimal> EstAnnualLivExp { get; set; }
        public Nullable<decimal> TotalAnnualExp { get; set; }
        public Nullable<decimal> ExistingOthIncome { get; set; }
        public Nullable<decimal> PensionGap { get; set; }
    
        public virtual tblLifeNeedAnalysi tblLifeNeedAnalysi { get; set; }
    }
}
