//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNeedSavingCalculator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNeedSavingCalculator()
        {
            this.tblNeedSaveCars = new HashSet<tblNeedSaveCar>();
            this.tblNeedSaveHouses = new HashSet<tblNeedSaveHouse>();
            this.tblNeedSaveOthers = new HashSet<tblNeedSaveOther>();
            this.tblNeedSaveTours = new HashSet<tblNeedSaveTour>();
            this.tblNeedSaveWeddings = new HashSet<tblNeedSaveWedding>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NeedAnalysisID { get; set; }
        public Nullable<int> Inflationrate { get; set; }
        public Nullable<decimal> AnnualSavingExp { get; set; }
        public Nullable<decimal> CurrReqTotal { get; set; }
        public Nullable<decimal> EstAmountTotal { get; set; }
        public Nullable<decimal> AvailableFund { get; set; }
        public Nullable<decimal> GapTotal { get; set; }
        public Nullable<decimal> MonthlySaveExp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedSaveCar> tblNeedSaveCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedSaveHouse> tblNeedSaveHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedSaveOther> tblNeedSaveOthers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedSaveTour> tblNeedSaveTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNeedSaveWedding> tblNeedSaveWeddings { get; set; }
        public virtual tblLifeNeedAnalysi tblLifeNeedAnalysi { get; set; }
    }
}
