//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrgStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrgStructure()
        {
            this.tblOrgOffices = new HashSet<tblOrgOffice>();
        }
    
        public decimal OrgStructureID { get; set; }
        public Nullable<decimal> OrganizationID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string LevelDefinition { get; set; }
        public Nullable<int> RepotrsToID { get; set; }
        public Nullable<decimal> ParentID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> StructureTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgOffice> tblOrgOffices { get; set; }
    }
}
