//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpportunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOpportunity()
        {
            this.tblOpportunityHistories = new HashSet<tblOpportunityHistory>();
        }
    
        public int OppurtunityID { get; set; }
        public int ContactID { get; set; }
        public Nullable<int> NeedAnalysisID { get; set; }
        public int StageID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AllocatedFrom { get; set; }
        public string Createdby { get; set; }
    
        public virtual tblContact tblContact { get; set; }
        public virtual tblLifeNeedAnalysi tblLifeNeedAnalysi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOpportunityHistory> tblOpportunityHistories { get; set; }
    }
}
