//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPlanRiderOccupationChart
    {
        public int ProductPlanRiderOccupationChartId { get; set; }
        public string Type { get; set; }
        public Nullable<int> ProductPlanRiderId { get; set; }
        public Nullable<decimal> OccupationId { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
