//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductRiderRateParameter
    {
        public int ProductRiderRateParameterId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> SumInsuredFrom { get; set; }
        public Nullable<int> SumInsuredTo { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string RelationShip { get; set; }
        public Nullable<decimal> SAMFactor { get; set; }
    }
}
