//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyMemberFamilyHistory
    {
        public decimal MemberFamilyHistoryID { get; set; }
        public decimal MemberID { get; set; }
        public string RelationshipWithMember { get; set; }
        public Nullable<int> PresentAge { get; set; }
        public Nullable<int> AgeAtDeath { get; set; }
        public string StateofHealth { get; set; }
        public string CauseofDeath { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> AnyPerson { get; set; }
        public Nullable<bool> Below_60_Age_Death { get; set; }
        public string Details { get; set; }
    
        public virtual tblPolicyMemberDetail tblPolicyMemberDetail { get; set; }
    }
}
