//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductRisk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductRisk()
        {
            this.tblPolicyRisks = new HashSet<tblPolicyRisk>();
        }
    
        public int ProductRiskID { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> Product_ID_PK { get; set; }
        public Nullable<int> InsurableTypeID { get; set; }
        public Nullable<int> RiskID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public Nullable<bool> IsBasic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyRisk> tblPolicyRisks { get; set; }
    }
}
