//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProspectInview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProspectInview()
        {
            this.tblProspectInterviewCriterias = new HashSet<tblProspectInterviewCriteria>();
        }
    
        public decimal ProspectInterviewID { get; set; }
        public Nullable<decimal> ProspectID { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string Interviewer { get; set; }
        public string InterviewResult { get; set; }
        public string ReferredTo { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Designation { get; set; }
        public string BranchCode { get; set; }
        public string ReportTo { get; set; }
        public string Travel { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalPoints { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string InterviewCode { get; set; }
        public string InterviewLevels { get; set; }
        public Nullable<decimal> CareerID { get; set; }
        public Nullable<decimal> PositionID { get; set; }
        public string ReceivedFrom { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> TotalPointsLevel2 { get; set; }
        public Nullable<int> TotalPointsLevel3 { get; set; }
        public Nullable<int> TotalPointsLevel4 { get; set; }
    
        public virtual tblProspect tblProspect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectInterviewCriteria> tblProspectInterviewCriterias { get; set; }
    }
}
