//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductParameter
    {
        public int ProductParameterId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<decimal> NumericValueFrom { get; set; }
        public Nullable<decimal> NumericValueTo { get; set; }
        public string StringValueFrom { get; set; }
        public string ListValue { get; set; }
        public string StringValueTo { get; set; }
    
        public virtual tblMasParameter tblMasParameter { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
