//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyMemberBenefitDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPolicyMemberBenefitDetail()
        {
            this.tblMemberBenefitOtherDetails = new HashSet<tblMemberBenefitOtherDetail>();
            this.tblMemberBenefitOtherDetails1 = new HashSet<tblMemberBenefitOtherDetail>();
        }
    
        public decimal MemberBenifitID { get; set; }
        public decimal MemberID { get; set; }
        public int BenifitID { get; set; }
        public string SumInsured { get; set; }
        public string Premium { get; set; }
        public string RelationShipWithProposer { get; set; }
        public string AssuredName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string LoadingAmount { get; set; }
        public string TotalPremium { get; set; }
        public Nullable<int> LoadingPerc { get; set; }
        public Nullable<int> LoadinPerMille { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberBenefitOtherDetail> tblMemberBenefitOtherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberBenefitOtherDetail> tblMemberBenefitOtherDetails1 { get; set; }
        public virtual tblPolicyMemberDetail tblPolicyMemberDetail { get; set; }
    }
}
