//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProspectOfficial
    {
        public decimal OfficialID { get; set; }
        public Nullable<decimal> ProspectID { get; set; }
        public string PrintName { get; set; }
        public Nullable<decimal> CareerLevelID { get; set; }
        public Nullable<decimal> DesignationID { get; set; }
        public Nullable<decimal> PositionID { get; set; }
        public string PrevAdvisorCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Designation { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public string OfficialCareerLevel { get; set; }
        public string OfficialPosition { get; set; }
        public string OfficialDesignation { get; set; }
    
        public virtual tblProspect tblProspect { get; set; }
    }
}
