//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyDocument
    {
        public decimal DocumentUploadID { get; set; }
        public Nullable<decimal> PolicyID { get; set; }
        public string DocumentType { get; set; }
        public string FileName { get; set; }
        public byte[] File { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FilePath { get; set; }
        public string ItemType { get; set; }
        public string MemberType { get; set; }
        public string Permission { get; set; }
        public string Remarks { get; set; }
        public string Decision { get; set; }
        public Nullable<bool> isNewDocumentAdded { get; set; }
    
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
