//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPlanRiderDiscountLoadingMap
    {
        public int ProductPlanRiderDiscountLoadingMapId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public Nullable<int> RelationId { get; set; }
        public string ChartType { get; set; }
        public string ChartCode { get; set; }
        public string RateType { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<int> CalculationOrder { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual tblRider tblRider { get; set; }
        public virtual tblMasProductPlan tblMasProductPlan { get; set; }
    }
}
