//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentInstrumentDetail
    {
        public decimal InstrumentPaymentID { get; set; }
        public Nullable<decimal> PaymentID { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMode { get; set; }
        public string InFavourOf { get; set; }
        public string InstrumentNo { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public Nullable<decimal> InstrumentAmount { get; set; }
        public Nullable<int> BankName { get; set; }
        public string BankBranch { get; set; }
        public string PGResponse { get; set; }
        public string RGIPaymentStatus { get; set; }
        public string Drawer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> isAllocation { get; set; }
        public string PayerType { get; set; }
        public string AccountNo { get; set; }
        public string MICRNo { get; set; }
    
        public virtual tblPayment tblPayment { get; set; }
    }
}
