//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyRisk
    {
        public decimal RiskID { get; set; }
        public decimal PolicyID { get; set; }
        public int RiskTypeID { get; set; }
        public Nullable<int> ProductRiskID { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public Nullable<decimal> ApplicableRate { get; set; }
        public Nullable<decimal> RiskPremium { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Loading { get; set; }
        public Nullable<decimal> DiscOrLoadedPremium { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> LoadedPremium { get; set; }
    
        public virtual tblProductRisk tblProductRisk { get; set; }
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
