//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyUWAllocation
    {
        public int PolicyUWAllocationID { get; set; }
        public Nullable<decimal> PolicyID { get; set; }
        public string AllocatedFrom { get; set; }
        public string AllocatedTo { get; set; }
        public Nullable<System.DateTime> AllocatedDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
