//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyUWRemarkHistory
    {
        public decimal PolicyUWRemarkHistoryID { get; set; }
        public Nullable<decimal> PolicyID { get; set; }
        public string Decision { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<System.DateTime> Commencement_Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsLoading { get; set; }
        public string Loading { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CommonID { get; set; }
    
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
