//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyCLAQuote
    {
        public decimal PolicyCLAQuoteId { get; set; }
        public decimal PolicyId { get; set; }
        public int LifeQQId { get; set; }
        public bool Active { get; set; }
    
        public virtual tblLifeQQ tblLifeQQ { get; set; }
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
