//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyMemberDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPolicyMemberDetail()
        {
            this.tblMemberDeviationInfoes = new HashSet<tblMemberDeviationInfo>();
            this.tblMemberLevelDecisions = new HashSet<tblMemberLevelDecision>();
            this.tblMemberLevelDecisionHistories = new HashSet<tblMemberLevelDecisionHistory>();
            this.tblMemberLifeStyleDetails = new HashSet<tblMemberLifeStyleDetail>();
            this.tblMemberQuestions = new HashSet<tblMemberQuestion>();
            this.tblPolicyMedicalHistories = new HashSet<tblPolicyMedicalHistory>();
            this.tblPolicyMemberBenefitDetails = new HashSet<tblPolicyMemberBenefitDetail>();
            this.tblPolicyMemberClaimInfoes = new HashSet<tblPolicyMemberClaimInfo>();
            this.tblPolicyMemberFamilyHistories = new HashSet<tblPolicyMemberFamilyHistory>();
            this.tblPolicyMemberInsuranceInfoes = new HashSet<tblPolicyMemberInsuranceInfo>();
            this.tblPolicyMemberTests = new HashSet<tblPolicyMemberTest>();
            this.tblQuestionDetails = new HashSet<tblQuestionDetail>();
        }
    
        public decimal MemberID { get; set; }
        public decimal PolicyID { get; set; }
        public string Salutation { get; set; }
        public string FULLName { get; set; }
        public string NameWithInitial { get; set; }
        public string PreferredName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public int RelationShipWithProposer { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public string OLDNICNO { get; set; }
        public string NEWNICNO { get; set; }
        public string MonthlyIncome { get; set; }
        public string CompanyName { get; set; }
        public string NatureOfDuties { get; set; }
        public string Nationality { get; set; }
        public string Mobile { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string AlternateMobileNo { get; set; }
        public string Home { get; set; }
        public string Work { get; set; }
        public Nullable<decimal> AdressID { get; set; }
        public Nullable<bool> IsPermanentAddrSameasCommAddr { get; set; }
        public Nullable<decimal> PermanetAddressId { get; set; }
        public Nullable<int> QuoteMemberid { get; set; }
        public string BasicSuminsured { get; set; }
        public string BasicPremium { get; set; }
        public string Assuredname { get; set; }
        public Nullable<int> NoofJsPolicies { get; set; }
        public Nullable<bool> IsOtherPolicy { get; set; }
        public Nullable<int> NoofOtherPolicies { get; set; }
        public string TotalDeath { get; set; }
        public string TotalAccidental { get; set; }
        public string TotalCritical { get; set; }
        public string TotalHospitalization { get; set; }
        public string TotalHospitalizationReimbursement { get; set; }
        public Nullable<bool> IsSameasProposerAddress { get; set; }
        public string UnitOfWeight { get; set; }
        public string UnitOfHeight { get; set; }
        public string MemberPremium { get; set; }
        public Nullable<bool> IsClaimExits { get; set; }
        public string Citizenship1 { get; set; }
        public string Citizenship2 { get; set; }
        public string ResidentialNationality { get; set; }
        public string ResidentialNationalityStatus { get; set; }
        public Nullable<bool> OccupationHazardousWork { get; set; }
        public string PassportNumber { get; set; }
        public string DrivingLicense { get; set; }
        public string USTaxpayerId { get; set; }
        public string CountryOccupation { get; set; }
        public string AdditionalPremium { get; set; }
        public string SpecifyResidental { get; set; }
        public string SpecifyHazardousWork { get; set; }
        public Nullable<bool> CitizenShip { get; set; }
        public Nullable<decimal> SAR { get; set; }
        public Nullable<decimal> FAL { get; set; }
        public Nullable<bool> AFC { get; set; }
        public string ClientCode { get; set; }
        public string Gender { get; set; }
        public string MaritialStatus { get; set; }
        public string SAM { get; set; }
        public Nullable<decimal> AnnualPremium { get; set; }
        public string BMIValue { get; set; }
        public Nullable<bool> OCR { get; set; }
        public Nullable<bool> OCRImageRecognition { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblAddress tblAddress1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberDeviationInfo> tblMemberDeviationInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberLevelDecision> tblMemberLevelDecisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberLevelDecisionHistory> tblMemberLevelDecisionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberLifeStyleDetail> tblMemberLifeStyleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMemberQuestion> tblMemberQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyMedicalHistory> tblPolicyMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyMemberBenefitDetail> tblPolicyMemberBenefitDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyMemberClaimInfo> tblPolicyMemberClaimInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyMemberFamilyHistory> tblPolicyMemberFamilyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyMemberInsuranceInfo> tblPolicyMemberInsuranceInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyMemberTest> tblPolicyMemberTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestionDetail> tblQuestionDetails { get; set; }
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
