//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblProductParameters = new HashSet<tblProductParameter>();
            this.tblProductQuestionMappings = new HashSet<tblProductQuestionMapping>();
            this.tblProductRiders = new HashSet<tblProductRider>();
            this.tblMasProductPlans = new HashSet<tblMasProductPlan>();
            this.tblProductPlanRiders = new HashSet<tblProductPlanRider>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> TypeOfProductId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> MinMOnthlyPremium { get; set; }
        public Nullable<decimal> MinQuarterlyPremium { get; set; }
        public Nullable<decimal> MinHalfYearlyPremium { get; set; }
        public Nullable<decimal> MinAnnualPremium { get; set; }
        public Nullable<decimal> MinBasicSumAssured { get; set; }
        public Nullable<int> Priority { get; set; }
        public string MinSurrenderYear { get; set; }
        public string MinTopUpYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductParameter> tblProductParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductQuestionMapping> tblProductQuestionMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductRider> tblProductRiders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasProductPlan> tblMasProductPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPlanRider> tblProductPlanRiders { get; set; }
    }
}
