//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyFinancialDetail
    {
        public decimal FinancialDetailsID { get; set; }
        public Nullable<decimal> PolicyID { get; set; }
        public Nullable<int> FinancierType { get; set; }
        public string FinancierName { get; set; }
        public string FinancierCity { get; set; }
        public string FinacierAddress { get; set; }
        public Nullable<decimal> PremisesID { get; set; }
        public string LoanAccountNo { get; set; }
        public string FinancierOthers { get; set; }
    
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
