//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProspect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProspect()
        {
            this.tblAuditDepartmentClearances = new HashSet<tblAuditDepartmentClearance>();
            this.tblBankInfoes = new HashSet<tblBankInfo>();
            this.tblEmergencyDetails = new HashSet<tblEmergencyDetail>();
            this.tblFinanceDepartmentClearances = new HashSet<tblFinanceDepartmentClearance>();
            this.tblHRMDepartmentClearances = new HashSet<tblHRMDepartmentClearance>();
            this.tblNomineeDetails = new HashSet<tblNomineeDetail>();
            this.tblPolicyRelationships = new HashSet<tblPolicyRelationship>();
            this.tblProspectEducations = new HashSet<tblProspectEducation>();
            this.tblProspectDocuments = new HashSet<tblProspectDocument>();
            this.tblProspectExams = new HashSet<tblProspectExam>();
            this.tblProspectGradeHistroys = new HashSet<tblProspectGradeHistroy>();
            this.tblProspectInviews = new HashSet<tblProspectInview>();
            this.tblProspectOfficials = new HashSet<tblProspectOfficial>();
            this.tblProspectReferences = new HashSet<tblProspectReference>();
            this.tblProspectTrainingDetails = new HashSet<tblProspectTrainingDetail>();
            this.tblSuspects = new HashSet<tblSuspect>();
        }
    
        public decimal ProspectID { get; set; }
        public string RecruitmentType { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NIC { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string OldAgentCode { get; set; }
        public string ProspectCode { get; set; }
        public string AgentType { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Profession { get; set; }
        public Nullable<decimal> SalesExperience { get; set; }
        public Nullable<decimal> IndustryExperience { get; set; }
        public string SLIINo { get; set; }
        public Nullable<decimal> PositionId { get; set; }
        public Nullable<decimal> DesignationId { get; set; }
        public Nullable<decimal> GradeId { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public Nullable<decimal> AltMobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> CommAddressId { get; set; }
        public Nullable<decimal> PermAddressId { get; set; }
        public Nullable<System.DateTime> SLIINoExpiryDate { get; set; }
        public string AgentCode { get; set; }
        public Nullable<decimal> StatusId { get; set; }
        public string SubStatusId { get; set; }
        public Nullable<decimal> InterviewCount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PreviousInsurerName { get; set; }
        public Nullable<decimal> MaritalStatus { get; set; }
        public Nullable<decimal> OfficePhNo { get; set; }
        public Nullable<decimal> ResidencePhNo { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string SpecifyProfession { get; set; }
        public string NeedforIncome { get; set; }
        public string othersforIncome { get; set; }
        public Nullable<bool> isNICClearnceOver { get; set; }
        public string ReceivedFrom { get; set; }
        public Nullable<bool> IsIntegartionServiceSuccess { get; set; }
        public Nullable<System.DateTime> InterviewScheduleDate { get; set; }
        public Nullable<System.DateTime> InterviewScheduleTime { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblAddress tblAddress1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuditDepartmentClearance> tblAuditDepartmentClearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankInfo> tblBankInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmergencyDetail> tblEmergencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFinanceDepartmentClearance> tblFinanceDepartmentClearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHRMDepartmentClearance> tblHRMDepartmentClearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNomineeDetail> tblNomineeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPolicyRelationship> tblPolicyRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectEducation> tblProspectEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectDocument> tblProspectDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectExam> tblProspectExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectGradeHistroy> tblProspectGradeHistroys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectInview> tblProspectInviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectOfficial> tblProspectOfficials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectReference> tblProspectReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProspectTrainingDetail> tblProspectTrainingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuspect> tblSuspects { get; set; }
    }
}
