//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyUWRemark
    {
        public decimal RemarkID { get; set; }
        public Nullable<decimal> PolicyID { get; set; }
        public string ReferredBy { get; set; }
        public string ReferralReason { get; set; }
        public string Decision { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<bool> IsExclusion { get; set; }
        public string Exclusion { get; set; }
        public Nullable<bool> IsLoading { get; set; }
        public string Loading { get; set; }
        public string UWRemarks { get; set; }
        public string Category { get; set; }
        public string NextUWPosition { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> NoofDays { get; set; }
    
        public virtual tblPolicy tblPolicy { get; set; }
    }
}
