//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProdRiderDocumentMap
    {
        public int ProdRiderDocMapId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public Nullable<decimal> SumInsuredFrom { get; set; }
        public Nullable<decimal> SumInsuredTo { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public Nullable<int> AgeTo { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<int> SUCFrom { get; set; }
        public Nullable<int> SUCTo { get; set; }
        public Nullable<int> PrevPremiumFrom { get; set; }
        public Nullable<int> PrevPremiumTo { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<bool> ForMDRT { get; set; }
    }
}
