//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPolicyMemberInsuranceInfo
    {
        public decimal MemberInsuranceID { get; set; }
        public decimal MemberID { get; set; }
        public string CompanyName { get; set; }
        public string Policy_ProposalNo { get; set; }
        public string TotalSIAtDeath { get; set; }
        public string AccidentalBenifit { get; set; }
        public string CriticalIllnessBenifit { get; set; }
        public string HospitalizationPerDay { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string HospitalizationReimbursement { get; set; }
    
        public virtual tblPolicyMemberDetail tblPolicyMemberDetail { get; set; }
    }
}
