//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProspectInterviewCriteria
    {
        public decimal ProspectInterviewCriteriaID { get; set; }
        public Nullable<decimal> ProspectInterviewID { get; set; }
        public Nullable<decimal> InterviewCategoryID { get; set; }
        public Nullable<decimal> Points { get; set; }
        public string Interviewer { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> InterviewID { get; set; }
        public string InterviewLevel_1 { get; set; }
        public string InterviewLevel_2 { get; set; }
        public string InterviewLevel_3 { get; set; }
        public string InterviewLevel_4 { get; set; }
        public Nullable<int> InterviewGuideTypeID { get; set; }
        public string Area { get; set; }
        public string Category { get; set; }
        public string Guide { get; set; }
    
        public virtual tblIMasInviewCaterory tblIMasInviewCaterory { get; set; }
        public virtual tblProspectInview tblProspectInview { get; set; }
        public virtual tblMasInterviewGuide tblMasInterviewGuide { get; set; }
    }
}
