//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionDetail
    {
        public decimal QuestionsId { get; set; }
        public Nullable<decimal> MemberID { get; set; }
        public Nullable<int> QID { get; set; }
        public string varcharFiled1 { get; set; }
        public Nullable<System.DateTime> DateFiled1 { get; set; }
        public string varcharFiled2 { get; set; }
        public Nullable<System.DateTime> DateFiled2 { get; set; }
        public string varcharFiled3 { get; set; }
        public string varcharFiled4 { get; set; }
        public string varcharFiled5 { get; set; }
        public string varcharFiled6 { get; set; }
        public string varcharFiled7 { get; set; }
        public string varcharFiled8 { get; set; }
        public string varcharFiled9 { get; set; }
        public Nullable<System.DateTime> DateFiled3 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string varcharFiled10 { get; set; }
        public string varcharFiled11 { get; set; }
        public Nullable<System.DateTime> DateFiled4 { get; set; }
        public string varcharFiled12 { get; set; }
        public string PAQvarcharFiled1 { get; set; }
        public string PAQvarcharFiled2 { get; set; }
        public string PAQvarcharFiled3 { get; set; }
        public string PAQvarcharFiled4 { get; set; }
        public string PAQvarcharFiled5 { get; set; }
        public string PAQvarcharFiled6 { get; set; }
        public string PAQvarcharFiled7 { get; set; }
        public string PAQvarcharFiled8 { get; set; }
        public string PAQvarcharFiled9 { get; set; }
        public string PAQvarcharFiled10 { get; set; }
        public string PAQvarcharFiled11 { get; set; }
        public string PAQvarcharFiled12 { get; set; }
        public string PAQYearFiled1 { get; set; }
        public string PAQYearFiled2 { get; set; }
        public string PAQYearFiled3 { get; set; }
        public string PAQAssetsTotal { get; set; }
        public string PAQLiabilitiesTotal { get; set; }
        public string PAQAssetsProperty { get; set; }
        public string PAQAssetsInvestment { get; set; }
        public string PAQAssetsEquities { get; set; }
        public string PAQAssetsOther { get; set; }
        public string PAQLiabilitiesMortgages { get; set; }
        public string PAQLiabilitiesLoans { get; set; }
        public string PAQLiabilitiesOthers { get; set; }
    
        public virtual tblPolicyMemberDetail tblPolicyMemberDetail { get; set; }
        public virtual tblMasLifeQuestionnaire tblMasLifeQuestionnaire { get; set; }
    }
}
