//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuoteIllustration
    {
        public decimal ID { get; set; }
        public string QuoteNo { get; set; }
        public Nullable<int> PolicyYear { get; set; }
        public Nullable<int> BasicPremium { get; set; }
        public Nullable<int> MainBenefitsPremium { get; set; }
        public Nullable<int> AdditionalBenefitsPremiums { get; set; }
        public Nullable<int> TotalPremium { get; set; }
        public Nullable<decimal> InvestmentACBalance { get; set; }
        public Nullable<decimal> SurrenderValue4 { get; set; }
        public Nullable<decimal> MonthlyDrawDown4 { get; set; }
        public Nullable<decimal> InvestmentACBalance8 { get; set; }
        public Nullable<decimal> SurrenderValue8 { get; set; }
        public Nullable<decimal> MonthlyDrawDown8 { get; set; }
        public Nullable<decimal> InvestmentACBalance12 { get; set; }
        public Nullable<decimal> SurrenderValue12 { get; set; }
        public Nullable<decimal> MonthlyDrawDown12 { get; set; }
        public Nullable<decimal> PensionBoosterDiv4 { get; set; }
        public Nullable<decimal> PensionBoosterDiv8 { get; set; }
        public Nullable<decimal> PensionBoosterDiv12 { get; set; }
        public Nullable<decimal> InvestmentACBalance5 { get; set; }
        public Nullable<decimal> InvestmentACBalance6 { get; set; }
        public Nullable<decimal> InvestmentACBalance7 { get; set; }
        public Nullable<decimal> InvestmentACBalance9 { get; set; }
        public Nullable<decimal> InvestmentACBalance10 { get; set; }
        public Nullable<decimal> InvestmentACBalance11 { get; set; }
        public Nullable<decimal> UnAllocatedPremium { get; set; }
        public Nullable<decimal> MonthlyDrawDown5 { get; set; }
        public Nullable<decimal> MonthlyDrawDown6 { get; set; }
        public Nullable<decimal> MonthlyDrawDown7 { get; set; }
        public Nullable<decimal> MonthlyDrawDown9 { get; set; }
        public Nullable<decimal> MonthlyDrawDown10 { get; set; }
        public Nullable<decimal> MonthlyDrawDown11 { get; set; }
    }
}
