//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuoteMemberDetial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuoteMemberDetial()
        {
            this.tblQuoteMemberBeniftDetials = new HashSet<tblQuoteMemberBeniftDetial>();
        }
    
        public int MemberID { get; set; }
        public int LifeQQID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public string Relationship { get; set; }
        public string AssuredName { get; set; }
        public Nullable<int> BasicSuminsured { get; set; }
        public string BasicPremium { get; set; }
        public string MemberPremium { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string NICNO { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> CurrentAge { get; set; }
    
        public virtual tblLifeQQ tblLifeQQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteMemberBeniftDetial> tblQuoteMemberBeniftDetials { get; set; }
    }
}
