//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRuleParameter
    {
        public int RuleParameterId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<decimal> NumericValueFrom { get; set; }
        public Nullable<decimal> NumericValueTo { get; set; }
        public string StringValueFrom { get; set; }
        public string StringValueTo { get; set; }
        public Nullable<System.DateTime> DateValueFrom { get; set; }
        public Nullable<System.DateTime> DateValueTo { get; set; }
        public string ListValueIn { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public string ExpressionFrom { get; set; }
        public string ExpressionTo { get; set; }
        public string NotExistsVal { get; set; }
        public string ExistsVal { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual tblRule tblRule { get; set; }
        public virtual tblMasRuleParameter tblMasRuleParameter { get; set; }
    }
}
