//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRider()
        {
            this.tblProductPlanRiderDiscountLoadingMaps = new HashSet<tblProductPlanRiderDiscountLoadingMap>();
            this.tblProductRiderParameters = new HashSet<tblProductRiderParameter>();
            this.tblProductRiderParameters1 = new HashSet<tblProductRiderParameter>();
            this.tblProductRiders = new HashSet<tblProductRider>();
            this.tblProductPlanRiders = new HashSet<tblProductPlanRider>();
        }
    
        public int RiderId { get; set; }
        public string RiderName { get; set; }
        public string RiderCode { get; set; }
        public Nullable<int> TypeOfProductId { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPlanRiderDiscountLoadingMap> tblProductPlanRiderDiscountLoadingMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductRiderParameter> tblProductRiderParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductRiderParameter> tblProductRiderParameters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductRider> tblProductRiders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPlanRider> tblProductPlanRiders { get; set; }
    }
}
