//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResourceCatagory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResourceCatagory()
        {
            this.tblResourceCategoryDetails = new HashSet<tblResourceCategoryDetail>();
            this.tblResourceCategoryDetails1 = new HashSet<tblResourceCategoryDetail>();
        }
    
        public int ResourceCatagoryPK { get; set; }
        public string ResourceCategory { get; set; }
        public Nullable<System.DateTime> Effectivedate { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResourceCategoryDetail> tblResourceCategoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResourceCategoryDetail> tblResourceCategoryDetails1 { get; set; }
    }
}
