//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRule()
        {
            this.tblRuleParameters = new HashSet<tblRuleParameter>();
        }
    
        public int RuleId { get; set; }
        public string RuleName { get; set; }
        public Nullable<int> RuleSetId { get; set; }
        public string RuleAction { get; set; }
        public Nullable<int> RuleSequence { get; set; }
        public string RuleDescription { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<int> RuleCategoryId { get; set; }
        public Nullable<int> RelationShip { get; set; }
        public string RuleApplyOn { get; set; }
        public string RefCode { get; set; }
        public string RuleLongDesc { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual tblMasRuleCategory tblMasRuleCategory { get; set; }
        public virtual tblRuleSet tblRuleSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRuleParameter> tblRuleParameters { get; set; }
    }
}
