//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public decimal TransactionID { get; set; }
        public string MethodName { get; set; }
        public string ControllerName { get; set; }
        public string TransactionName { get; set; }
        public string TransactionIdentifier { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string UserName { get; set; }
        public string Application { get; set; }
        public string ActionType { get; set; }
        public string SessionID { get; set; }
    }
}
