//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserProductPermission
    {
        public decimal ProductPermID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public Nullable<bool> IsCDTAllowed { get; set; }
        public Nullable<int> BackdationDays { get; set; }
        public Nullable<int> QuoteValidity { get; set; }
        public Nullable<bool> IsCDAllowed { get; set; }
        public Nullable<bool> PaymentLink { get; set; }
        public Nullable<int> AgeOfVehicle { get; set; }
        public Nullable<int> AdvanceDays { get; set; }
        public Nullable<bool> isNBAllowed { get; set; }
        public Nullable<bool> isROAllowed { get; set; }
        public Nullable<bool> isUsedAllowed { get; set; }
        public Nullable<bool> isHOPrintAllowed { get; set; }
    
        public virtual User User { get; set; }
    }
}
