//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUWProposal
    {
        public decimal UWProposalID { get; set; }
        public string ProposalNo { get; set; }
        public string QuoteNumber { get; set; }
        public string UWLoginID { get; set; }
        public string Status { get; set; }
        public string IsModified { get; set; }
        public string UWRemarks { get; set; }
    }
}
