//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Repository.AIAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUWReason
    {
        public int ReasonID { get; set; }
        public string ItemCode { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Reason { get; set; }
        public string Reason2 { get; set; }
    }
}
