//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Integration.Services.EmailandSMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailIntegrationTemplete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailIntegrationTemplete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIA.Life.Integration.Services.EmailandSMS.EmailIntegrationTemplete", typeof(EmailIntegrationTemplete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;   
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;title&gt;Emailer&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    @font-face
        ///    {
        ///      font-family:&apos;AIAEverest-Regular&apos;;
        ///      src:url(&apos;../Font/AIAEverest-Regular.otf&apos;);
        ///    }
        ///      /* Default CSS */
        ///      body,#body_style {mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
    }
}
