//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Integration.Services.EmailandSMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SMSIntegrationTemplete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMSIntegrationTemplete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIA.Life.Integration.Services.EmailandSMS.SMSIntegrationTemplete", typeof(SMSIntegrationTemplete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We have emailed you the completed Financial Need Analysis. Please speak to your Wealth Planner/FPE on txtWPMobileNo for any clarification - AIA Insurance                                     txtSMSEnvironment
        ///.
        /// </summary>
        internal static string S001 {
            get {
                return ResourceManager.GetString("S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We have emailed you the life insurance quotation. Please speak to your Wealth Planner/FPE on txtWPMobileNo for any clarification - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S002 {
            get {
                return ResourceManager.GetString("S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, Your life insurance application txtProposalNo is successfully submitted. It is being processed and we will update you on the progress. Call 0112310310 for clarifications - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S003 {
            get {
                return ResourceManager.GetString("S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We have emailed you a copy of the life insurance proposal form. Call  0112310310 for any clarifications.
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S004 {
            get {
                return ResourceManager.GetString("S004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPoS Notice: Life proposal txtProposalNo introduced by you has been received by life underwriting department today - Life Ops.
        /// </summary>
        internal static string S005 {
            get {
                return ResourceManager.GetString("S005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Life proposal txtProposalNo is pending. Please check NexGen iPoS - Web or emails for further details and inform the customer - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S006 {
            get {
                return ResourceManager.GetString("S006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We need more information to process your life insurance application txtProposalNo. We have emailed you the details. Your Wealth Planner/FPE  will contact you shortly - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S007 {
            get {
                return ResourceManager.GetString("S007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We have emailed you some additional requirements needed to process your life insurance application. Call 0112310310 for clarifications - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S008 {
            get {
                return ResourceManager.GetString("S008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, Thank you for submitting us the outstanding requirements. We have emailed you the details. Your Wealth Planner/FPE will contact you shortly - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S009 {
            get {
                return ResourceManager.GetString("S009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Proposal txtProposalNo - Thank you for submitting us the outstanding requirements. Please check NexGen iPoS - Web or emails for further details and inform the customer - Life Ops 
        /// txtSMSEnvironment.
        /// </summary>
        internal static string S010 {
            get {
                return ResourceManager.GetString("S010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	Dear txtSalutation. txtSurname, Kind reminder on the further requirements under your insurance application. These requirements are essential to process your application - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S011 {
            get {
                return ResourceManager.GetString("S011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: The premium amount of Dh txtPremium is needed to accept the Proposal (No: txtProposalNo) - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S012 {
            get {
                return ResourceManager.GetString("S012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Proposal txtProposalNo will be cancelled on txtProposalEndDate  due to non-completion of due requirements. Please comply with the requirements ASAP - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S013 {
            get {
                return ResourceManager.GetString("S013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We are compelled to cancel your life insurance proposal txtProposalNo on txtProposalEndDate  unless due requirements are received. Please comply with the due requirements at your earliest - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S014 {
            get {
                return ResourceManager.GetString("S014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Proposal txtProposalNo has been declined due to txtHealthconditionOccupation - Life Ops 
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S015 {
            get {
                return ResourceManager.GetString("S015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, Regret to inform you of our inability to issue a life insurance policy on your life based on the findings of your txtHealthconditionOccupation - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S016 {
            get {
                return ResourceManager.GetString("S016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Proposal txtProposalNo has been postponed due to txtHealthconditionOccupation - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S017 {
            get {
                return ResourceManager.GetString("S017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, Regret to inform you of our inability to issue a life cover on your life at this juncture based on your txtHealthconditionOccupation. We are prepared to reconsider our decision in txtMonths months - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S018 {
            get {
                return ResourceManager.GetString("S018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Proposal txtProposalNo has been withdrawn due to non-submission of pending requirements - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S019 {
            get {
                return ResourceManager.GetString("S019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, Your life insurance Proposal txtProposalNo was cancelled due to non-submission of due requirements. Call 0112310310 for clarifications - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S020 {
            get {
                return ResourceManager.GetString("S020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Proposal txtProposalNo has been cancelled as requested by the customer - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S021 {
            get {
                return ResourceManager.GetString("S021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: Congratulations! Your Proposal txtProposalNo is accepted - Life Ops
        ///txtSMSEnvironment
        ///.
        /// </summary>
        internal static string S022 {
            get {
                return ResourceManager.GetString("S022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, We are happy to announce that your life insurance proposal has been accepted. Your Insurance Policy will be sent to you soon - AIA Insurance
        /// txtSMSEnvironment.
        /// </summary>
        internal static string S023 {
            get {
                return ResourceManager.GetString("S023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Dear txtSalutation. txtSurname, Your e-policy txtPolicyNo has been emailed to you. Call 0112310310 for any clarifications - AIA Insurance
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S024 {
            get {
                return ResourceManager.GetString("S024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///iPoS Notice: e-policy txtPolicyNo has been emailed to the customer - Life Ops
        ///txtSMSEnvironment.
        /// </summary>
        internal static string S025 {
            get {
                return ResourceManager.GetString("S025", resourceCulture);
            }
        }
    }
}
