//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Life.Integration.Services.AIAOnlinePremiumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.aviva.com/", ConfigurationName="AIAOnlinePremiumService.Life")]
    public interface Life {
        
        // CODEGEN: Generating message contract since element name policyNo from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/uploadPaymentRequest", ReplyAction="http://ws.aviva.com/Life/uploadPaymentResponse")]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponse uploadPayment(AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/uploadPaymentRequest", ReplyAction="http://ws.aviva.com/Life/uploadPaymentResponse")]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponse> uploadPaymentAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name paymentDate from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/paymentCountRequest", ReplyAction="http://ws.aviva.com/Life/paymentCountResponse")]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponse paymentCount(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/paymentCountRequest", ReplyAction="http://ws.aviva.com/Life/paymentCountResponse")]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponse> paymentCountAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest request);
        
        // CODEGEN: Generating message contract since element name policyNo from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/paymentReversalRequest", ReplyAction="http://ws.aviva.com/Life/paymentReversalResponse")]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponse paymentReversal(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/paymentReversalRequest", ReplyAction="http://ws.aviva.com/Life/paymentReversalResponse")]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponse> paymentReversalAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest request);
        
        // CODEGEN: Generating message contract since element name policyNo from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/validatePolicyNoRequest", ReplyAction="http://ws.aviva.com/Life/validatePolicyNoResponse")]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponse validatePolicyNo(AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aviva.com/Life/validatePolicyNoRequest", ReplyAction="http://ws.aviva.com/Life/validatePolicyNoResponse")]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponse> validatePolicyNoAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadPayment", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequestBody Body;
        
        public uploadPaymentRequest() {
        }
        
        public uploadPaymentRequest(AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class uploadPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string policyNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string instType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string instNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        public uploadPaymentRequestBody() {
        }
        
        public uploadPaymentRequestBody(string policyNo, string instType, string instNo, double amount, string clientID, string password) {
            this.policyNo = policyNo;
            this.instType = instType;
            this.instNo = instNo;
            this.amount = amount;
            this.clientID = clientID;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadPaymentResponse", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponseBody Body;
        
        public uploadPaymentResponse() {
        }
        
        public uploadPaymentResponse(AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class uploadPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public uploadPaymentResponseBody() {
        }
        
        public uploadPaymentResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentCount", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequestBody Body;
        
        public paymentCountRequest() {
        }
        
        public paymentCountRequest(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class paymentCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string paymentDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientID;
        
        public paymentCountRequestBody() {
        }
        
        public paymentCountRequestBody(string paymentDate, string clientID) {
            this.paymentDate = paymentDate;
            this.clientID = clientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentCountResponse", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponseBody Body;
        
        public paymentCountResponse() {
        }
        
        public paymentCountResponse(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class paymentCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public paymentCountResponseBody() {
        }
        
        public paymentCountResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentReversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentReversal", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequestBody Body;
        
        public paymentReversalRequest() {
        }
        
        public paymentReversalRequest(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class paymentReversalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string policyNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string instType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string instNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        public paymentReversalRequestBody() {
        }
        
        public paymentReversalRequestBody(string policyNo, string instType, string instNo, double amount, string clientID, string password) {
            this.policyNo = policyNo;
            this.instType = instType;
            this.instNo = instNo;
            this.amount = amount;
            this.clientID = clientID;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentReversalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentReversalResponse", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponseBody Body;
        
        public paymentReversalResponse() {
        }
        
        public paymentReversalResponse(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class paymentReversalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public paymentReversalResponseBody() {
        }
        
        public paymentReversalResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validatePolicyNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validatePolicyNo", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequestBody Body;
        
        public validatePolicyNoRequest() {
        }
        
        public validatePolicyNoRequest(AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validatePolicyNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string policyNo;
        
        public validatePolicyNoRequestBody() {
        }
        
        public validatePolicyNoRequestBody(string policyNo) {
            this.policyNo = policyNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validatePolicyNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validatePolicyNoResponse", Namespace="http://ws.aviva.com/", Order=0)]
        public AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponseBody Body;
        
        public validatePolicyNoResponse() {
        }
        
        public validatePolicyNoResponse(AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validatePolicyNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public validatePolicyNoResponseBody() {
        }
        
        public validatePolicyNoResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LifeChannel : AIA.Life.Integration.Services.AIAOnlinePremiumService.Life, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LifeClient : System.ServiceModel.ClientBase<AIA.Life.Integration.Services.AIAOnlinePremiumService.Life>, AIA.Life.Integration.Services.AIAOnlinePremiumService.Life {
        
        public LifeClient() {
        }
        
        public LifeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LifeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LifeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponse AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.uploadPayment(AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest request) {
            return base.Channel.uploadPayment(request);
        }
        
        public string uploadPayment(string policyNo, string instType, string instNo, double amount, string clientID, string password) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequestBody();
            inValue.Body.policyNo = policyNo;
            inValue.Body.instType = instType;
            inValue.Body.instNo = instNo;
            inValue.Body.amount = amount;
            inValue.Body.clientID = clientID;
            inValue.Body.password = password;
            AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponse retVal = ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).uploadPayment(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponse> AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.uploadPaymentAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest request) {
            return base.Channel.uploadPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentResponse> uploadPaymentAsync(string policyNo, string instType, string instNo, double amount, string clientID, string password) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.uploadPaymentRequestBody();
            inValue.Body.policyNo = policyNo;
            inValue.Body.instType = instType;
            inValue.Body.instNo = instNo;
            inValue.Body.amount = amount;
            inValue.Body.clientID = clientID;
            inValue.Body.password = password;
            return ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).uploadPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponse AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.paymentCount(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest request) {
            return base.Channel.paymentCount(request);
        }
        
        public int paymentCount(string paymentDate, string clientID) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequestBody();
            inValue.Body.paymentDate = paymentDate;
            inValue.Body.clientID = clientID;
            AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponse retVal = ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).paymentCount(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponse> AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.paymentCountAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest request) {
            return base.Channel.paymentCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountResponse> paymentCountAsync(string paymentDate, string clientID) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentCountRequestBody();
            inValue.Body.paymentDate = paymentDate;
            inValue.Body.clientID = clientID;
            return ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).paymentCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponse AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.paymentReversal(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest request) {
            return base.Channel.paymentReversal(request);
        }
        
        public int paymentReversal(string policyNo, string instType, string instNo, double amount, string clientID, string password) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequestBody();
            inValue.Body.policyNo = policyNo;
            inValue.Body.instType = instType;
            inValue.Body.instNo = instNo;
            inValue.Body.amount = amount;
            inValue.Body.clientID = clientID;
            inValue.Body.password = password;
            AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponse retVal = ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).paymentReversal(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponse> AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.paymentReversalAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest request) {
            return base.Channel.paymentReversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalResponse> paymentReversalAsync(string policyNo, string instType, string instNo, double amount, string clientID, string password) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.paymentReversalRequestBody();
            inValue.Body.policyNo = policyNo;
            inValue.Body.instType = instType;
            inValue.Body.instNo = instNo;
            inValue.Body.amount = amount;
            inValue.Body.clientID = clientID;
            inValue.Body.password = password;
            return ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).paymentReversalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponse AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.validatePolicyNo(AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest request) {
            return base.Channel.validatePolicyNo(request);
        }
        
        public int validatePolicyNo(string policyNo) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequestBody();
            inValue.Body.policyNo = policyNo;
            AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponse retVal = ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).validatePolicyNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponse> AIA.Life.Integration.Services.AIAOnlinePremiumService.Life.validatePolicyNoAsync(AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest request) {
            return base.Channel.validatePolicyNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoResponse> validatePolicyNoAsync(string policyNo) {
            AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest inValue = new AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequest();
            inValue.Body = new AIA.Life.Integration.Services.AIAOnlinePremiumService.validatePolicyNoRequestBody();
            inValue.Body.policyNo = policyNo;
            return ((AIA.Life.Integration.Services.AIAOnlinePremiumService.Life)(this)).validatePolicyNoAsync(inValue);
        }
    }
}
